### ISSUE TITLE
Possibility to perform simulations using weights learned from FORCE

### ISSUE THREAD

**Issue by dmnburrows** [zhenruiliao/tension#32]
Hi there,

Very interested in using your package for FORCE! I had a methodological question which wasn't clear from the paper/github - lets say I am using FORCE to learn the recurrent weights in the reservoir pool to produce neuronal activity traces (like in the zebrafish example). Once the weights have been learned, I want to be able to perform simulations, for example to see how changing the weights of certain neurons in the network changes the network activity - is there a way in tension to simulate this (without any learning occurring)?

Thanks!

**Comment by lubin-liu** [comment]
One can access the recurrent weights of a layer via: `esn_layer.recurrent_kernel`. With tensorflow tensors you cannot do slice assignments like with numpy, so to modify the weights you would have to use `esn_layer.recurrent_kernel.assign(...)` with a new tensor that has the modified weights (see docs [tf.Variable.assign](https://www.tensorflow.org/api_docs/python/tf/Variable#assign), note that this modifies the tensor in memory so it's not reversible). Then, you can go `force_model.predict(...)` to get the output with the new weights. Be careful not to re-assign the weights like `esn_layer.recurrent_kernel = ....` which will decouple the weights used in the forward pass and training.

I would note that this is not a typical use case; I noticed that after `assign`, the name of the tensor has changed. I'm unsure if this will cause any problems inside tensorflow itself. This will for sure not work if `force_model.fit()` is not called beforehand i.e. the model was not trained prior to modifying the weights.

**Comment by dmnburrows** [comment]
Great, thanks! This seems to work
